<?php

function service_log_help($path, $arg) {
  switch ($path) {
    case "admin/help#service_log":
      return '<p>' . t("Displays links to nodes created on this date") . '</p>';
      break;
  }
} 

function service_log_block_info() {
  $blocks['current_posts'] = array(
    // The name that will appear in the block list.
    'info' => t('Current posts'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}